### ISSUE TITLE
Using DublinCore metadata elements in RSS/Xml

### ISSUE THREAD

**Issue by mstksg** [sof/feed#2]
I'm not sure if I'm using things correctly, but how are the DublinCore metadata elements supposed to be used with the XML/RSS data types?  I can't seem to find anything in the source.  Are we supposed to just manually write functions to convert `DCItem`s into `Element`s using `infoToTag`?  I don't really mind doing this (and could offer a patch to add it into the library), but is there a reason why this functionality has been excluded from this library?  What is the "intended" usage?

**Comment by sof** [comment]
Sorry about the delay. For RSS1, you can include DC extras with a number of RSS1 elements, e.g., Text.RSS1.Syntax.Item has a "itemDC" field which holds a list of them. Similarly for the other RSS1 element types.

Only supported for RSS1; are DC elements used with other RSS variants?

**Comment by mstksg** [comment]
Ah I see it now.  Yeah, I saw the DC elements in an RSS feed I was modeling mine after and did not notice that it was specified as RSS 1.0.  Didn't realize they were an RSS1 thing only.

**Comment by sof** [comment]
There's nothing stopping you from using those in other, "newer" RSS formats, I suppose. But the common DC elements did get direct replacements in these formats, avoiding the reliance on the DC vocabulary.

(I'll take the liberty of closing this issue, hope that's cool :) )
