### ISSUE TITLE
fails to find enclosures in feed http://redecentralize.org/podcast/feed.rss

### ISSUE THREAD

**Issue by joeyh** [sof/feed#5]
Similar to #3, getItemEnclosure fails on this feed.

This time around, it seems we have length="" breaking things. Feed creators sure seem to have lots of ways to break something so simple!

**Comment by sof** [comment]
"Breaking things" -- what behaviour are you expecting?

**Comment by joeyh** [comment]
sof wrote:

> "Breaking things" -- what behaviour are you expecting?

The library is able to parse this rss feed, using eg parseFeedFromFile.
However, getItemEnclosure returns Nothing for each of the feedItems,
which is not ideal since each of the items does have an enclosure, 
although with a bogus size of "".

## 

see shy jo

**Comment by sof** [comment]
The following works for me with HEAD,

foo$ readFile "ff.rss" >>= \ ls -> return $ any (not.isJust) $ map Text.Feed.Query.getItemEnclosure (Text.Feed.Query.feedItems $ fromJust $ Text.Feed.Import.parseFeedString ls)

**Comment by joeyh** [comment]
sof wrote:

> The following works for me with HEAD,
> 
> foo$ readFile "ff.rss" >>= \ ls -> return $ any (not.isJust) $ map
> Text.Feed.Query.getItemEnclosure (Text.Feed.Query.feedItems $ fromJust $
> Text.Feed.Import.parseFeedString ls)

Apologies, I'm a bit under the weather today and seem to have forgotten to
cabal install after pulling current HEAD. It does work.

## 

see shy jo

**Comment by sof** [comment]
That's good, mystery solved. If the 'length' attribute is provided, but it isn't liked by 'reads', it'll be (silently) mapped to Nothing.

It makes sense for the parsers for these different RSS formats be liberal & accepting. But, having them at least report warnings when feeds sidestep the expected attribute types, and engages in other non-conforming behaviour, would have been helpful here, I suppose. No immediate plans to work on this though.
